name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.19.0  # 指定较老的 buildx 版本

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5  # 使用 build-push-action 替代 bake-action
        with:
          context: .
          file: .container/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/owl:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/owl:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/owl:latest,mode=max
