name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-chengdu.aliyuncs.com  # 替换为您的阿里云容器镜像服务地址
          username: ${{ secrets.ALIYUN_USERNAME }}     # 阿里云访问账号
          password: ${{ secrets.ALIYUN_PASSWORD }}     # 阿里云访问密码

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          files: |
            .container/docker-compose.yml
          push: true
          set: |
            *.cache-from=type=registry,ref=registry.cn-chengdu.aliyuncs.com/fuck-test/owl:latest
            *.cache-to=type=registry,ref=registry.cn-chengdu.aliyuncs.com/fuck-test/owl:latest,mode=max
            *.tags=registry.cn-chengdu.aliyuncs.com/fuck-test/owl:latest
