name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # 当main分支有推送时触发
  pull_request:
    branches: [ "main" ]  # 当有PR到main分支时触发
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          files: |
            .container/docker-compose.yml
          push: true
          set: |
            *.cache-from=type=registry,ref=your-dockerhub-username/owl:latest
            *.cache-to=type=registry,ref=your-dockerhub-username/owl:latest,mode=max
            *.tags=your-dockerhub-username/owl:latest
